FORMAT: 1A
 
# To-do

todoを登録、追加、更新するためのAPIです

# Group Task
 
## Tasks [/users/{user_id}/tasks]

+ id
+ user_id
+ title
+ due_date - ISO8601形式で表されるタスクの期限日

+ Parameters
    + user_id (string) - firebaseのuid

### タスクの全件取得 [GET]

+ Request

    + Headers

            authorization: {token}

+ Response 200 (application/json)

    + Body

            [
                {
                    "id": 1,
                    "user_id": "user_id",
                    "title": "task_title1",
                    "due_date": "2019-06-04T18:30:40"
                },
                {
                    "id": 2,
                    "user_id": "user_id",
                    "title": "task_title2",
                    "due_date": "2019-06-04T18:30:40"
                },
                {
                    "id": 3,
                    "user_id": "user_id",
                    "title": "task_title3",
                    "due_date": "2019-06-04T18:30:40"
                }
            ]

### タスクの登録 [POST]

+ Request
    + Headers

            authorization: {token}
            content-type: application/json

    + Body

            {
                "title": "your_task_title",
                "due_date": "2019-06-04T18:30:40"
            }

+ Response 200

    + Headers

            location: /users/{user_id}/tasks/{new_task_id}

### タスクの全件削除[DELETE]

+ Response 204

## Task [/users/{user_id}/tasks/{task_id}]

+ id
+ user_id
+ title
+ due_date - ISO8601形式で表されるタスクの期限日

+ Parameters

    + user_id (string) - firebaseのuid
    + task_id (number) - taskのid

### タスクの取得 [GET]

+ Request

    + Headers

            authorization: {token}

+ Response 200 (application/json)

        {
            "id": 1,
            "user_id": "user_id",
            "title": "task_title1",
            "due_date": "2019-06-04T18:30:40"
        }

### タスクの更新 [PUT]

+ Request

    + Headers

            authorization: {token}
            content-type: application/json
    + Body

            {
                "title": "your_task_title",
                "due_date": "2019-06-04T18:30:40"
            }
    
+ Response 200

### タスクの削除[DELETE]

+ Request

    + Headers

            authorization: {token}
    
+ Response 204